# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NT-aJt_PERYR6l-Lc4lqlx-aa1FysCO9
"""

import pandas as pd

import numpy as np

df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Servo%20Mechanism.csv')

df.describe()

df.head()

df.info()

df.shape

df.columns

df[['Motor']].value_counts()

df[['Screw']].value_counts()

df.replace({'Motor':{'A':0,'B':1,'C':2,'D':3,'E':4}},inplace=True)
df.replace({'Screw':{'A':0,'B':1,'C':2,'D':3,'E':4}},inplace=True)

y=df['Class']

x=df[['Motor', 'Screw', 'Pgain', 'Vgain']]

x.shape
y.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.3,random_state=2529)

from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(x_train,y_train)

model.intercept_

model.coef_

y_predict=model.predict(x_test)

from sklearn.metrics import mean_absolute_percentage_error

mean_absolute_percentage_error(y_test,y_predict)

